=pod

=head1 NAME

Mover::Form::Role::Address - Address Field for the mover project.

=head1 VERSION

version 0.1

=head2 options_state
  Builds the Options for US states. (NY New York,  AL Alabama etc).

=head2 validate_zip
 Called automatically to validate Zip Code using Regexp::Common qw/zip/.

=head1 AUTHOR

Austin Kenny <aibistin.cionnaith@gmail.com>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2013 by Austin Kenny.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

